version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - ~/docker/mysql_data:/var/lib/mysql
  
  redis:
    image: redis:7.2-alpine
    container_name: redis-6381
    ports:
      - "6381:6379" # map port host 6381 -> container redis 6379
    restart: always
    volumes:
      - ~/docker/redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  mysql_data:
    driver: local
