// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

// Account
type GoDbUser struct {
	// Account ID
	UsrID uint32
	// Email
	UsrEmail string
	// Phone number
	UsrPhone string
	// Username
	UsrName string
	// Password
	UsrPassword string
	// Created time
	UsrCreatedAt int32
	// Updated time
	UsrUpdatedAt int32
	// Created IP
	UsrCreatedIpAt string
	// Last login time
	UsrLastLoginAt int32
	// Last login IP
	UsrLastLoginIpAt string
	// Login time
	UsrLoginAt int32
	// Status: 1: enable, 0: disable, -1: delete
	UsrStatus bool
}
