// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGoDbUserRole = "go_db_user_roles"

// GoDbUserRole mapped from table <go_db_user_roles>
type GoDbUserRole struct {
	UserUUID string `gorm:"column:user_uuid;primaryKey" json:"user_uuid"`
	RoleID   int64  `gorm:"column:role_id;primaryKey" json:"role_id"`
}

// TableName GoDbUserRole's table name
func (*GoDbUserRole) TableName() string {
	return TableNameGoDbUserRole
}
