// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGoDbRole = "go_db_roles"

// GoDbRole mapped from table <go_db_roles>
type GoDbRole struct {
	ID   int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name string `gorm:"column:name;not null" json:"name"`
	Note string `gorm:"column:note" json:"note"`
}

// TableName GoDbRole's table name
func (*GoDbRole) TableName() string {
	return TableNameGoDbRole
}
