server:
  port: 8000

mysql:
  user: root
  password: 123456
  host: localhost
  port: 3306
  dbname: mydb
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600

log:
  level: debug
  file: ./storages/logs/dev.001.log
  max_size: 500
  max_backups: 3
  max_age: 28
  compress: true

redis:
  host: 127.0.0.1
  port: 6381
  password:
  db: 0