server:
  port: 8000

mysql:
  user: admin
  password: Toan207@207
  host: localhost
  port: 3306
  dbname: ecommerce
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600

log:
  level: debug
  file: ./storages/logs/dev.001.log
  max_size: 500
  max_backups: 3
  max_age: 28
  compress: true