server:
  port: 8000
  mode: dev

mysql:
  user: root
  password: 123456
  host: mysql-container
  port: 3306
  dbname: mydb
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600

log:
  level: debug
  file: ./storages/logs/dev.001.log
  max_size: 500
  max_backups: 3
  max_age: 28
  compress: true

redis:
  host: redis-6381
  port: 6379
  password:
  db: 0

smtp:
  host: "smtp.gmail.com"
  port: 587
  user: "euchoice.notify@gmail.com"
  password: "pckv xhnh xlbf xqqb"
  from: "euchoice.notify@gmail.com"